version: "3.9"

services:
  config-service:
    image: floodcast/floodcast:latest
    container_name: floodcast-config
    command: >
      uv run --package config-server --with fastapi --
      fastapi run services/config-server/app/main.py
      --host 0.0.0.0 --port 8000
    environment:
      SERVICE_NAME: config-server
    ports:
      - "8003:8000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway-service:
    image: floodcast/floodcast:latest
    container_name: floodcast-gateway
    command: >
      uv run --package gateway --with fastapi --
      fastapi run services/gateway/app/main.py
      --host 0.0.0.0 --port 8000
    environment:
      SERVICE_NAME: gateway
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      config-service:
        condition: service_healthy

  weather-data-service:
    image: floodcast/floodcast:latest
    container_name: floodcast-weather
    command: >
      uv run --package weather-data --with fastapi --
      fastapi run services/weather-data/app/main.py
      --host 0.0.0.0 --port 8000
    environment:
      SERVICE_NAME: weather-data
    ports:
      - "8001:8000"
    restart: always
    depends_on:
      config-service:
        condition: service_healthy

  alert-service:
    image: floodcast/floodcast:latest
    container_name: floodcast-alert
    command: >
      uv run --package alert --with fastapi --
      fastapi run services/alert/app/main.py
      --host 0.0.0.0 --port 8000
    environment:
      SERVICE_NAME: alert
    ports:
      - "8007:8000"
    restart: always
    depends_on:
      config-service:
        condition: service_healthy

networks:
  default:
    name: floodcast-network

