apiVersion: v1
kind: Service
metadata:
  name: flow-data-service
spec:
  selector:
    app: flow-data-service
  ports:
    - name: local-port
      port: 8000
      targetPort: 8000
      protocol: TCP
