apiVersion: v1
kind: Service
metadata:
  name: weather-data-service
spec:
  selector:
    app: weather-data-service
  ports:
    - name: local-port
      port: 8000
      targetPort: 8000
      protocol: TCP
